# Generated by Django 3.0.3 on 2020-02-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('mot_de_passe', models.CharField(max_length=40, verbose_name='mot_de_passe')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=4, verbose_name='nom_classe')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dept', models.CharField(max_length=30, verbose_name='nom_dept')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=40, verbose_name='prenom')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.IntegerField(verbose_name='telephone')),
                ('statut', models.CharField(default='simple', max_length=40, verbose_name='statut')),
                ('mot_de_passe', models.CharField(max_length=40, verbose_name='mot_de_passe')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=40, verbose_name='prenom')),
                ('nom', models.CharField(max_length=20, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.IntegerField(verbose_name='telephone')),
                ('statut', models.CharField(default='simple', max_length=40, verbose_name='statut')),
                ('mot_de_passe', models.CharField(max_length=40, verbose_name='mot_de_passe')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.Departement'),
        ),
    ]
