# Generated by Django 3.0.3 on 2020-02-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrateur',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='classe',
        ),
        migrations.AddField(
            model_name='departement',
            name='chef_dept',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='authentification.Professeur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='departement',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='authentification.Departement'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='genre',
            field=models.CharField(default='genre', max_length=20),
        ),
        migrations.AddField(
            model_name='eleve',
            name='profil',
            field=models.ImageField(default="C:/Users/Diamalay'Tech/Pictures/Capture.png", upload_to=''),
        ),
        migrations.AddField(
            model_name='professeur',
            name='genre',
            field=models.CharField(default='genre', max_length=20),
        ),
        migrations.AddField(
            model_name='professeur',
            name='profil',
            field=models.ImageField(default="C:/Users/Diamalay'Tech/Pictures/Capture.png", upload_to=''),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='mot_de_passe',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='statut',
            field=models.CharField(default='simple', max_length=40),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='mot_de_passe',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='prenom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='statut',
            field=models.CharField(default='simple', max_length=40),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
