# Generated by Django 3.0.3 on 2020-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20200211_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom_classe',
            field=models.CharField(max_length=10, verbose_name='nom_classe'),
        ),
    ]
