# Generated by Django 3.0.2 on 2020-02-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_auto_20200211_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('mdp', models.CharField(max_length=40)),
            ],
        ),
    ]
