# Generated by Django 3.0.2 on 2020-02-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_remove_eleve_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='genre',
            field=models.CharField(default='genre', max_length=20, null=True),
        ),
    ]
