# Generated by Django 3.0.2 on 2020-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_auto_20200222_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='statut',
        ),
        migrations.AddField(
            model_name='professeur',
            name='respClasse',
            field=models.CharField(default='Non', max_length=40),
        ),
        migrations.AddField(
            model_name='professeur',
            name='respDept',
            field=models.CharField(default='Non', max_length=40),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='profil',
            field=models.ImageField(default='/photos/avatar1.png/', upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='profil',
            field=models.ImageField(default='/photos/avatar1.png/', upload_to='photos/'),
        ),
    ]
