# Generated by Django 3.0.2 on 2020-02-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_matiere_module_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ue',
            name='total_ECTS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ue',
            name='total_coef',
            field=models.IntegerField(default=0),
        ),
    ]
