# Generated by Django 3.0.2 on 2020-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_auto_20200224_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='nbre_modules',
            field=models.IntegerField(default=0),
        ),
    ]
