# Generated by Django 3.0.2 on 2020-02-29 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_casematiere_casemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('commentaire', models.CharField(default='Jour non commenté', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='casematiere',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.Jour'),
        ),
    ]
