# Generated by Django 3.0.2 on 2020-03-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_auto_20200229_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casematiere',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='casemodule',
            name='heure_fin',
        ),
    ]
