from django.urls import path
from authentification import views

urlpatterns = [
     path('connexion', views.LoginView, name='connexion'),
     path('connexion/<str:erreur>/', views.LoginViewErreur, name='connexionErreur'),
     path('inscription/', views.Inscription, name='inscription'),
     path('enregistrementE/', views.dashboardNouvelEleve, name='enregistrementEleve'),
     path('enregistrementP/', views.dashboardNouveauProfesseur, name='enregistrementProfesseur'),
     path('deconnexion/', views.LogoutView, name='deconnexion'),
     path('dashboard/', views.dashboard, name='dashboard'),
     path('listeEleve/<str:classe>/<int:user>/<int:cle>/', views.ListeEleve, name='listeEleve'),
     path('listeEleves/<int:user>/<int:cleUser>/', views.listeEleves, name='listeEleves'),
     path('listeDepartement/<int:cle>/', views.GestionDepartement, name='GestionDepartement'),
     path('listeProfesseur/<int:cle>/', views.ListeProf, name='listeProf'),
     path('listeClasse/<int:cle>/', views.ListeClasse, name='listeClasse'),
     path('profilEleve/<int:cle>/', views.ProfilEleve, name='profilEleve'),
     path('profilProfesseur/<int:cle>/', views.ProfilProf, name='profilProf'),
     path('CahierDeTexte/<int:user>/<int:cleUser>/', views.CahierDeTexte, name='CDT'),
     path('CahierDeTexteClasse/<int:user>/<int:cleUser>/<int:cleClasse>/', views.CahierDeTexteClasse, name='CDTClasse'),
     path('EmploiDuTemps/<int:user>/<int:cleUser>/', views.EmploiDuTemps, name='EDT'),
     path('EmploiDuTempsClasse/<int:user>/<int:cleUser>/<int:cleClasse>/', views.EmploiDuTempsClasse, name='EDTClasse'),
     path('NouvelEmploiDuTempsClasse/<int:cleUser>/<int:cleClasse>/', views.newEDT, name='newEDT'),
     path('Maquette/<int:user>/<int:cleUser>/', views.Maquette, name='Maquette'),
     path('MaquetteClasse/<int:user>/<int:cleUser>/<int:cleClasse>/', views.MaquetteClasse, name='MaquetteClasse'),
     path('addModule/<int:cleUser>/<int:cleClasse>/', views.AddModule, name='addModule'),
     path('editModule/<int:cleUser>/<int:cleClasse>/<int:cleModule>/', views.EditModule, name='editModule'),
     path('saveModule/<int:cleUser>/<int:cleClasse>/<int:cleModule>/', views.SaveModule, name='saveModule'),
     path('deleteModule/<int:cleUser>/<int:cleClasse>/<int:cleModule>/', views.DeleteModule, name='deleteModule'),
     path('addUE/<int:cleUser>/<int:cleClasse>/', views.AddUE, name='addUE'),
     path('editUE/<int:cleUser>/<int:cleClasse>/<int:cleUE>/', views.EditUE, name='editUE'),
     path('saveUE/<int:cleUser>/<int:cleClasse>/<int:cleUE>/', views.SaveUE, name='saveUE'),
     path('deleteUE/<int:cleUser>/<int:cleClasse>/<int:cleUE>/', views.DeleteUE, name='deleteUE'),
     path('addMatiere/<int:cleUser>/<int:cleClasse>/', views.AddMatiere, name='addMatiere'),
     path('editMatiere/<int:cleUser>/<int:cleClasse>/<int:cleMatiere>/', views.EditMatiere, name='editMatiere'),
     path('saveMatiere/<int:cleUser>/<int:cleClasse>/<int:cleMatiere>/', views.SaveMatiere, name='saveMatiere'),
     path('deleteMatiere/<int:cleUser>/<int:cleClasse>/<int:cleMatiere>/', views.DeleteMatiere, name='deleteMatiere'),
]